application:
  name: "spring-boot-scala-example"
  description: "An example Spring Boot app using Scala"

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always

logging:
  file:
    name: logs/spring-boot-scala-example.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe
    username: grego
    password: springboot
    jetty:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  jdbc:
    template:
      max-rows: 500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  default_page_size: 20
  query_read_timeout: 1000
  query_write_timeout: 1000
